version: '3'

services:
    proxy:
        build: .
        ports:
            - "8080:8080"
        restart: always

    wrk:
        build: wrk/
        depends_on:
            - "proxy"
        volumes:
            - ./wrk/scripts:/scripts